import Mathlib.GroupTheory.Perm.Cycle.Concrete
import Mathlib.GroupTheory.SpecificGroups.Alternating
import Mathlib.GroupTheory.GroupAction.MultipleTransitivity

/-!
# M₂₃ in Mathlib — statements and proof plan

Companion to `formal/M23Formal` (which is dependency-free and fully proved).
This file states the *real* formalization targets against Mathlib. The `sorry`s
are ordered by expected difficulty; each carries a proof plan.

Status: skeleton. Build inside a Mathlib project (see repo README):
  lake new m23mathlib math && cp this file over M23mathlib/Basic.lean
-/

open Equiv

namespace M23Mathlib

/-- `(1,11)(2,23)(3,8)(4,16)(5,21)(7,20)(15,19)(18,22)`, 0-based. -/
def g1 : Perm (Fin 23) :=
  c[0, 10] * c[1, 22] * c[2, 7] * c[3, 15] * c[4, 20] * c[6, 19] * c[14, 18] * c[17, 21]

/-- The paper's 23-cycle `g₂`, 0-based. -/
def g2 : Perm (Fin 23) :=
  c[0, 1, 10, 9, 15, 8, 5, 2, 22, 18, 19, 13, 20, 16, 3, 7, 21, 4, 17, 14, 12, 6, 11]

/-- The paper's 23-cycle `g₃`, 0-based. -/
def g3 : Perm (Fin 23) :=
  c[0, 1, 2, 3, 9, 10, 11, 6, 18, 17, 7, 5, 8, 15, 16, 20, 21, 4, 13, 19, 12, 14, 22]

/-- The paper's identity `g₁ g₂ g₃ = 1`. Mathlib's `Perm` multiplication is
function composition (left action), matching the paper's convention.

Kernel `decide` exceeds the recursion limit on cycle-notation products, so we
use `native_decide` (trusts the compiler). A kernel-only proof of the same
fact, via image lists, is in `formal/M23Formal` — so nothing here rests on
compiler trust alone. -/
theorem triple_product : g1 * g2 * g3 = 1 := by native_decide

/-- The Mathieu group M₂₃, as the subgroup generated by the paper's elements. -/
def M23 : Subgroup (Perm (Fin 23)) := Subgroup.closure {g1, g2}

/-- Both generators are even, so M₂₃ ⊆ A₂₃.
Plan: `Subgroup.closure_le` + `Perm.mem_alternatingGroup` + `decide` on signs. -/
theorem M23_le_alternating : M23 ≤ alternatingGroup (Fin 23) := by
  sorry

/-- |M₂₃| = 10 200 960 = 2⁷·3²·5·7·11·23.
Plan: formalize a stabilizer-chain (Schreier–Sims) certificate: a chain of
point stabilizers with verified orbit sizes 23, 22, 21, 20, 48, with the last
stabilizer trivial. Each orbit size is checked by `decide`/`native_decide` on
explicit coset-representative data; the order is the product. This is the
right general-purpose infrastructure to contribute to Mathlib — it would
certify *any* permutation group order. -/
theorem card_M23 : Nat.card M23 = 10200960 := by
  sorry

/-- M₂₃ is 4-transitive on `Fin 23`.
Plan: `MultipleTransitivity` API (`MulAction.IsMultiplyPretransitive`);
witness tuples produced by the stabilizer chain. -/
theorem M23_four_transitive :
    MulAction.IsMultiplyPretransitive M23 (Fin 23) 4 := by
  sorry

/-- M₂₃ is simple.
Plan: 4-transitive + order bookkeeping via classical simplicity criteria
(e.g. Jordan's theorem route), or port the standard Steiner-system proof.
Hardest of the group-theory targets. -/
theorem M23_simple : IsSimpleGroup M23 := by
  sorry

/-!
## The arithmetic frontier (not yet stated formally)

The paper's Theorem 1.1 — there is a Galois extension of ℚ with group M₂₃ —
needs: number fields of degree 23, Galois closures, Dedekind's theorem on
factorization mod p vs. cycle types, discriminants, and a formal interface to
the classification of transitive groups of degree 23. Mathlib has the Galois
theory; the missing pieces are Dedekind's theorem in usable generality and the
transitive-groups classification. Milestones in that order.
-/

end M23Mathlib
